### ISSUE TITLE
Bioconductor version doesn't match R version

### ISSUE THREAD

**Issue by thomaskelder** [Bioconductor/bioc_docker#1]
The current bioconductor image seems to have a mismatch between the R version (3.2.0) and Bioconductor (3.0).

I pulled the latest bioconductor image from docker registry and used the following dockerfile to build an image with additional packages installed:

```
FROM bioconductor/release_core:latest

RUN Rscript -e "BiocInstaller::biocLite('limma')"
```

The output shows the following warnings:

```
Bioconductor version 3.0 (BiocInstaller 1.16.4), ?biocLite for help
A new version of Bioconductor is available after installing the most recent
  version of R; see http://bioconductor.org/install
Warning message:
BiocInstaller version 3.0 is too old for R version 3.2.0;
  remove.packages("BiocInstaller") then
  source("http://bioconductor.org/biocLite.R") 
```

The image does build, but the bioconductor version it contains seems out of date (should be 3.1).

**Comment by dtenenba** [comment]
This is fixed now, please pull again. Thanks for the report.
