### ISSUE TITLE
rake not working

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/bioc_docker#12]
I'm trying to build and push the `devel_core` image to my docker hub but rake isn't working for me. I have used `docker login` and edited my `auth.yml` file. This is the error I'm getting:

```
> rake devel_core
running task devel_base...
rake aborted!
LoadError: cannot load such file -- docker
/home/user/Documents/github/bioc_docker/Rakefile:26:in `setup_docker'
/home/user/Documents/github/bioc_docker/Rakefile:66:in `block (3 levels) in <top (required)>'
Tasks: TOP => devel_core => devel_base
(See full trace by running task with --trace)
```

`rake, version 10.5.0`
`Docker version 1.12.5, build 7392c3b`

Thanks, MR

**Comment by dtenenba** [comment]
Install the `docker` ruby library:

    gem install docker

**Comment by LiNk-NY** [comment]
Thanks for the response. 

I'm getting this error now: 
```
NoMethodError: undefined method `url=' for Docker:Module
/home/user/Documents/github/bioc_docker/Rakefile:33:in `setup_docker'
/home/user/Documents/github/bioc_docker/Rakefile:66:in `block (3 levels) in <top (required)>'
Tasks: TOP => devel_core => devel_base
(See full trace by running task with --trace)
```
Seems like the `docker` gem hasn't been tested with Ubuntu 16.04? (missing url method)
Thanks Dan!

**Comment by dtenenba** [comment]
Sorry, I gave you the wrong command. Uninstall the `docker` package:

    gem uninstall docker

And either install `docker-api` as follows:

    gem install docker-api

or do the recommended thing which I should have said first, which is to install bundler:

    gem install bundler # you can skip this if `which bundler` returns something

Then:

    bundle install

Will install the dependencies in the `Gemfile`.

**Comment by LiNk-NY** [comment]
I ran into a snag with `json 1.8.1` but I used `bundle update` and it's working now with `json 2.0.2`. Thanks again!
