### ISSUE TITLE
Core MS container

### ISSUE THREAD

**Issue by lgatto** [Bioconductor/bioc_docker#14]
@sneumann - as far as I understand, specifying `Metabolomics` and `Proteomics` biocViews in the [config file](https://github.com/phnmnl/bioc_docker/blob/master/config.yml#L32-L36) is going to pull all packages that have these tags. I think we should specify a limited number of core MS packages; I would suggest we start with 

- `ProtGenerics`
- `mzR`
- `msdata` (experiment package)

and then progressively add anything that would be relevant for the metabolomics and proteomics containers.

**Comment by mtmorgan** [comment]
Just my two cents that yes, a hand-curated container is better, and maybe a key benefit of 'community-curate' docker images.

**Comment by sneumann** [comment]
Hi, I hacked the install.R script
For that container to take the intersection, changed from ANY to ALL somewhere, resulting in 9 joint packages. Yours Steffen

---
I blame Android for the brevity and typos


---- Laurent Gatto schrieb ----


@sneumann<https://github.com/sneumann> - as far as I understand, specifying Metabolomics and Proteomics biocViews in the config file<https://github.com/phnmnl/bioc_docker/blob/master/config.yml#L32-L36> is going to pull all packages that have these tags. I think we should specify a limited number of core MS packages; I would suggest we start with

  *   ProtGenerics
  *   mzR
  *   msdata (experiment package)

and then progressively add anything that would be relevant for the metabolomics and proteomics containers.

**Comment by lgatto** [comment]
If there are not that many candidates, I suggest we list them one by one for clarity.

**Comment by lgatto** [comment]
I am also wondering if we shouldn't have an `mscore` based on `base`, rather than `core` and curate a minimal list of required dependencies. Something like 
```r
pkgs <- c("biocViews", "ProtGenerics", "mzR", "msdata",
          "BiocParallel", "knitr", "rmarkdown", "httr", "RCul", "XML",
          "zlibbioc")
```

**Comment by lgatto** [comment]
@sneumann - what do you think of having this lighter, hand-curated `mscore` container? I am happy to amend the metabolomics config to make it work.
