### ISSUE TITLE
Rakefile: assigned but unused variable

### ISSUE THREAD

**Issue by lgatto** [Bioconductor/bioc_docker#16]
This [line](https://github.com/Bioconductor/bioc_docker/blob/master/Rakefile#L53)
```
vcontainer_name = version_name + "_" + container_name
```
creates a `vcontainer` variable that is never used. Not sure if it's a superfluous `v` or something else is going on.

**Comment by lshep** [comment]
I believe this is a legacy and not needed.  I'll test delete and remove when I make the changes for making the directory structure.

**Comment by lgatto** [comment]
Thanks!
