### ISSUE TITLE
RStudio update needed on devel docker containers?

### ISSUE THREAD

**Issue by seandavi** [Bioconductor/bioc_docker#18]
I see this when working with the current devel_core2 container:

```
R graphics engine version 12 is not supported by this version of RStudio. The Plots tab will be disabled until a newer version of RStudio is installed. 
```

**Comment by lshep** [comment]
I don't believe this to be a problem with the docker but with the version of Rstudio you are using. As far as I am aware we don't download the Rstudio version on the docker image;  did you do this separately?

**Comment by seandavi** [comment]
Thanks, @lshep.  The bioc_devel containers look like they inherit from rocker/rstudio-daily.  I'll focus there instead.  Sorry about the noise.

**Comment by lshep** [comment]
There was an update on their docker on monday,  I don't know if it happened before or after our build so I will try rebuilding our images as well.

**Comment by seandavi** [comment]
Does this help?

https://docs.docker.com/docker-hub/builds/#repository-links

**Comment by stianlagstad** [comment]
I realize this is not a Bioconductor issue, but do any of you have tips for how to get around it? I'm getting the error with both Rstudio version 1.0.136 and with version 1.1.105 (which I believe is the daily build).
