### ISSUE TITLE
Package dependencies

### ISSUE THREAD

**Issue by lgatto** [Bioconductor/bioc_docker#2]
As far as I can see, the `Suggests` dependencies of a package are not included in the docker containers. Would you consider adding these? It would be nice to be able to run all examples and vignette code of the packages available in a container.

**Comment by vobencha** [comment]
Unfortunately we are short staffed right now and can't get to this. I'd accept a patch/pull request if you want to submit one.

**Comment by lshep** [comment]
Sorry for the delayed response.  In generally we wanted to have just the basic necessities provided.  Adding all the suggested packages could make the docker images very large and unmanageable.  We feel like the user can add the suggested packages as needed after loading the docker container.
