### ISSUE TITLE
Errors building Cairo: libx11-dev dependency

### ISSUE THREAD

**Issue by lgatto** [Bioconductor/bioc_docker#26]
Tracking the issues with the `proteomics2` container, I identified the following issue when running 

```r
biocLite("Cairo")
```

```
gcc -std=gnu99 -I/usr/local/lib/R/include -DNDEBUG -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12   -I. -Iinclude  -I/usr/local/include  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c xlib-backend.c -o xlib-backend.o
xlib-backend.c:34:74: fatal error: X11/Intrinsic.h: No such file or directory
 #include <X11/Intrinsic.h>      /*->    Xlib.h  Xutil.h Xresource.h .. */
                                                                          ^
compilation terminated.
/usr/local/lib/R/etc/Makeconf:159: recipe for target 'xlib-backend.o' failed
make: *** [xlib-backend.o] Error 1
ERROR: compilation failed for package ‘Cairo’
* removing ‘/usr/local/lib/R/site-library/Cairo’

The downloaded source packages are in
	‘/tmp/Rtmp1hA2tS/downloaded_packages’
Warning message:
In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘Cairo’ had non-zero exit status
```

I think that adding `libx11-dev` to the list of `apt-get install` packages will fix this. 

Any suggestions whether it would be best to add in a lower-level container such as `base`?

**Comment by lshep** [comment]
My initial feeling is that it should be added in your docker script.  The base packages don't need this dependency nor do any of the packages we have on our core container; so it feels more appropriate to add it where it is being used.   
@mtmorgan thoughts?  Maybe it should be added to base?

**Comment by lgatto** [comment]
Ok, I'll add it to the `proteomics` container. If there's interest, I'll make the change wherever is useful.

**Comment by sneumann** [comment]
+1 lib*-dev should be as late as possible, but that might be in a parent container 
(almost) all of its children require it, and if the task of that intermediate container 
is to accumulate as much common stuff between its children. Just my 2c, Steffen

**Comment by lgatto** [comment]
It appears that it's actually `libxt-dev` that is missing and stops `Cairo` to install. I hope to get that fixed soon and send a PR that fixes the `proteomics2` containers.
