### ISSUE TITLE
Documentation: describe the build system 

### ISSUE THREAD

**Issue by sneumann** [Bioconductor/bioc_docker#3]
Hi, it would be great to document the build system setup, 
i.e. to use `rake` to create the actual Dockerfiles in `out/*`

**Comment by vobencha** [comment]
I agree, good idea. Unfortunately we're short staffed right now and can't get to this. I would accept a patch/pull request if you want to submit one. 

We've also discussed reducing the number of containers we support and focusing on the core and / or base images. Opinions?

**Comment by sneumann** [comment]
Hi, already partially done in the pull request for the metabolomics packages.
regarding the core/base support and dropping the others: what about 
getting community support for them ? Like, you just got for metabolomics :-)

**Comment by vobencha** [comment]
I'll post on the list to see if anyone is interested.
