### ISSUE TITLE
release_protmetcore2 failling to build due to bioassayR, ChemmineR

### ISSUE THREAD

**Issue by sneumann** [Bioconductor/bioc_docker#36]
https://hub.docker.com/r/bioconductor/release_protmetcore2/builds/bqcyh3r5s3dsfqfwqjbvpew/
````
1: In install.packages(pkgs = doing, lib = lib, ...) : installation of package ‘ChemmineR’ had non-zero exit status 
2: In install.packages(pkgs = doing, lib = lib, ...) : installation of package ‘bioassayR’ had non-zero exit status
````

ChemmineR fails because of `library(gridExtra) : there is no package called ‘gridExtra’`

**Comment by lgatto** [comment]
In addition, many linux packages could be dropped from the `protmetcore` Docker file, as they are already included in `mscore`.
