### ISSUE TITLE
devel_protmetcore2: annotation packages missing

### ISSUE THREAD

**Issue by sneumann** [Bioconductor/bioc_docker#41]
This is the reason for the failure of devel_protmetcore2:

```
Warning: unable to access index for repository 
https://bioconductor.org/packages/3.6/data/annotation/src/contrib:
  cannot open URL 'https://bioconductor.org/packages/3.6/data/annotation/src/contrib/PACKAGES'
Warning: dependencies ‘org.Hs.eg.db’, ‘org.Mm.eg.db’, ‘org.Rn.eg.db’, ‘GO.db’, ‘hgu133plus2.db’, ‘hgu133a.db’, ‘KEGG.db’ are not available
```
and indeed, I get a 404 for https://bioconductor.org/packages/3.6/data/annotation/src/contrib/PACKAGES
while the same works for 3.5. I thing devel_protmetcore2 will fix itself once this works again. 

Yours,
Steffen

**Comment by lshep** [comment]
I will investigate this issue

**Comment by sneumann** [comment]
PACKAGES is available today, and devel_protmetcore2 did built fine.
