### ISSUE TITLE
New protcore container

### ISSUE THREAD

**Issue by lgatto** [Bioconductor/bioc_docker#47]
I added a new `protcore` container as an intermediate before building all proteomics packages, as the later always times out. 

@lshep - could you add it to the docker hub, or tell me how to do it. Thanks!

**Comment by lshep** [comment]
Is there a reason these extra packages couldn't have been added into the already existing mscore or protmetcore container?

**Comment by lgatto** [comment]
`mscore` contains a minimal set of manually curated mass spectrometry packages and `protmetcore` the packages common to proteomics and metabolomics biocViews. The extra packages are not relevant for metabolomics; I'm not sure it would be useful to bloat the metabolomics containers. @sneumann, what do you think?

**Comment by lshep** [comment]
I set up and am trying to build the devel version now. If that is successful I will work on the release version

**Comment by lshep** [comment]
The devel_protcore2 container has built successfully.  I triggered a rebuild of the devel_proteomics2 since it is now its parent.  
The release_protcore2 is queued for building when the devel_proteomics completes.

**Comment by lgatto** [comment]
Ok, great and thank! Unless already done, I will set up the `proteomics` container to use `protcore`. I am also going to add/change some packages in `protcore` to reflect the most downloaded packages.

**Comment by lshep** [comment]
The new containers are up on docker hub :   bioconductor/devel_protcore2  and bioconductor/release_protcore2.
