### ISSUE TITLE
change logs

### ISSUE THREAD

**Issue by Drwhit** [Bioconductor/bioc_docker#49]
Is there a place to see change logs in each version?

**Comment by lshep** [comment]
The dockerhub repository links give the build details - if you click on one of the builds it will show you what was installed.   Also depending if you are talking about release or devel - Devel are updated weekly to have the latest versions of the packages appropriate for the associated R version - release does not change except if there was a new version of R or bug corrections to packages.  Any major change or system dependency will be documented through the commits as normal on a github repository.
