### ISSUE TITLE
ddalpha is victim of OOM killer

### ISSUE THREAD

**Issue by sneumann** [Bioconductor/bioc_docker#50]
Hi, 
the last builds of `devel_metabolomics2` are killed during the automated builds. 
https://hub.docker.com/r/bioconductor/devel_metabolomics2/builds/bpstlewv4gnnrvyeclryhn8/
Reason is that linking ddalpha.so consumes large (>=6 GB) of RAM, 
and the hub.docker build machines probably have a limit set.
```
...
g++ -std=gnu++11 -shared -L/usr/local/lib/R/lib -L/usr/local/lib -o ddalpha.so AlphaProcedure.o Common.o DKnn.o HD.o Knn.o Mahalanobis.o OjaDepth.o Polynomial.o PotentialDepth.o ProjectionDepth.o SimplicialDepth.o TukeyDepth.o ZonoidDepth.o asa047.o ddalpha.o depth.fd.o init.o stdafx.o -lgfortran -lm -lquadmath -L/usr/local/lib/R/lib -lR [91minstalling to /usr/local/lib/R/site-library/ddalpha/libs
byte-compile and prepare package for lazy loading
Killed
```
Locally the `devel_metabolomics2` builds just fine. 

Ideas ?

Yours, Steffen

**Comment by lshep** [comment]
I think it is a limitation on dockerhub itself -   I haven't found much besides this post on stackoverflow 

https://stackoverflow.com/questions/31158913/is-there-any-limit-on-pull-number-in-docker-hub

**Comment by sneumann** [comment]
Hi, I think that link is about the resulting image size.

The issue here is that the gcc link step is killed, and guess that the dockerhub build has RAM limits set, E.g. 2GB.

Yours Steffen

---
I blame Android for the brevity and typos

**Comment by pokotylo** [comment]
Hi, I have recently fixed this issue in ddalpha. Now it does not consume that much memory during byte-compilation.
