### ISSUE TITLE
add new cytometry container

### ISSUE THREAD

**Issue by mikejiang** [Bioconductor/bioc_docker#69]
I will submit PR shortly. Let me what else I need to do in order for it to appear in https://hub.docker.com/r/bioconductor

**Comment by lshep** [comment]
I will look over the pull request and make sure it compiles correctly and  set up the dockerhub repos under the bioconductor dockerhub account.  If anything looks out of sorts I'll let you know.  It may be a week or two until fully functional under the Bioconductor account.

**Comment by lshep** [comment]
I merged the pull requests and created the repos on docker hub and kicked off initial builds -  it should be active now.  
There is a slight issue with docker hub linking builds to upstream images that we used in the past but I'm looking into this -  
Please test the docker images for devel_cytometry2 and release_cytometry2  and let me know if there are any issues.

**Comment by mikejiang** [comment]
Work perfectly!Thanks a lot!

**Comment by mikejiang** [comment]
Can we update http://bioconductor.org/help/docker/ as well?

**Comment by lshep** [comment]
Yep I'll do that now.  Thanks!

**Comment by mikejiang** [comment]
I saw the container hasn't been updated since 2 months ago https://hub.docker.com/r/bioconductor/devel_cytometry2/builds
I thought it was updated weekly?

**Comment by lshep** [comment]
Its suppose to.  When dockerhub updated their site the autobuilds deactivated somehow.  I'm working on it.  The devel dockers are also broken currently until rocker has a 3.6.0 tag https://github.com/Bioconductor/bioc_docker/issues/79

**Comment by mikejiang** [comment]
Good to know. Please keep me posted. Thanks a lot!
