### ISSUE TITLE
devel_mscore2: BiocVersion not available for R-devel

### ISSUE THREAD

**Issue by sneumann** [Bioconductor/bioc_docker#79]
Hi, in https://cloud.docker.com/u/bioconductor/repository/registry-1.docker.io/bioconductor/devel_mscore2/builds/d7a4ddb7-52ab-494a-b572-e88142c3d283
we get 
```
ok <- BiocManager::install(pkgs_to_install, update=FALSE, ask=FALSE) %in% rownames(installed.packages())
Bioconductor version 3.9 (BiocManager 1.30.4), R Under development (unstable)
(2019-03-30 r76304)
Installing package(s) 'BiocVersion', 'biocViews', 'ProtGenerics', 'mzR',
...
	‘/tmp/RtmpvBEE7T/downloaded_packages’
Warning messages:
1: package ‘BiocVersion’ is not available (for R Under development) 
```
Although it looks to be perfectly (well, one warning) availavle:
http://bioconductor.org/checkResults/devel/bioc-LATEST/BiocVersion/

**Comment by lshep** [comment]
I think this is because R-devel now is set for R3.7  as they have already branched for R3.6  however the rocker/rstudio has not updated and does not have a base image for 3.6.0 yet. So when our devel dockers pull R-devel is recognizing as R 3.7 and causes ERRORS.  Until the R3.6.0 image becomes available in rocker/rstudio, I think the devel images will be broken.  I'll open an issue with rocker.

**Comment by lshep** [comment]
https://github.com/rocker-org/rocker-versioned/issues/132

**Comment by lshep** [comment]
So as per their answer and closing of the issue immediately,  The docker images for devel will be broken until they release the new tag with the R-3.6.

**Comment by sneumann** [comment]
So in that brief time window between R-devel reporting itself as `3.7.0` 
and release of updated rocker-versioned images  
we would have to relax `Depends: R (>= 3.6.0), R (< 3.7.0)`
in https://www.bioconductor.org/packages/devel/bioc/html/BiocVersion.html
to `R (<= 3.7.0)` and switch back to strict `R (< 3.7.0)` upon the R release ? What does @mtmorgan say here ? Yours, Steffen

**Comment by sneumann** [comment]
Indeed, hacking the Dockerfile works:
```
# invalidates cache every 24 hours
ADD http://master.bioconductor.org/todays-date /tmp/

# Hack for https://github.com/Bioconductor/bioc_docker/issues/79
RUN git clone https://git.bioconductor.org/packages/BiocVersion
RUN sed -i -e 's/, R (< /, R (<= /' BiocVersion/DESCRIPTION 
RUN R CMD INSTALL BiocVersion

RUN R -f /tmp/install.R
```

In fact, we could do the above hack by default in the Dockerfile:
in this environment, we KNOW the R versions, because we either 
explicitly specified the rocker-versioned in `release_core2`,
OR `rocker/rstudio:devel` is either the desired one, or the devel version that just switched numbering.
This should only be done in the `devel_core2` image. 

Then we don't need to change the shipped `BiocVersion`.

Yours, Steffen

**Comment by sneumann** [comment]
Apologies, that commit did not go to a PR, was too late over here. 
Note that I didn't change the `bioc_docker/out` files.
Yours, Steffen

**Comment by sneumann** [comment]
This should be adressed by https://github.com/Bioconductor/bioc_docker/pull/83
Yours, Steffen
