### ISSUE TITLE
proteomics: Rchemcpp fails due to staged install

### ISSUE THREAD

**Issue by sneumann** [Bioconductor/bioc_docker#86]
`ERROR: absolute paths in ‘libs/Rchemcpp.so’ include the temporary installation directory: please report to the package maintainer and use ‘--no-staged-install’`

**Comment by lshep** [comment]
from the mailing list it looks like this package will be deprecated

**Comment by sneumann** [comment]
Yes, my after me prodding :-) 
and already excluded here in the `install.R`. 
Yours, Steffen
