### ISSUE TITLE
bioconductor/devel_base2:latest image --  libssl1.0.2 issue

### ISSUE THREAD

**Issue by nturaga** [Bioconductor/bioc_docker#91]
```
docker run -p 8787:8888 -e PASSWORD=bioc bioconductor/devel_base2:latest              ✔
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] add: executing...
Nothing additional to add
[cont-init.d] add: exited 0.
[cont-init.d] userconf: executing...
[cont-init.d] userconf: exited 0.
[cont-init.d] done.
[services.d] starting services
/usr/lib/rstudio-server/bin/rserver: error while loading shared libraries: libssl.so.1.0.2: cannot open shared object file: No such file or directory
[services.d] done.
rsession: no process found
```

Issue carries forward to https://github.com/Bioconductor/bioconductor_full/issues/18

**Comment by nturaga** [comment]
It seems the bug is introduced by introducing the library `libmariadb-dev-compat` in the devel version. 

This seems to be adding a version of `libssl.so.1.0.0` in `/usr/lib/x86_64-linux-gnu`. And this is causing the problem with rstudio. 

If I remove this library `libmariadb-dev-compat` from the Dockerfile, there are only, (rstudio works)

```
root@dfabeee53986:/usr/lib/x86_64-linux-gnu# ls libssl*
libssl.a  libssl.so  libssl.so.1.1
```

Next step is to investigate why we need `libmariadb-dev-compat`.

**Comment by lshep** [comment]
you originally had libmariadb-client-lgpl-dev in the dockerfile but this is what also broke in devel a few weeks ago.  While you were away @mtmorgan and I chose this as the replacement.   If you have a better dependency, I'm fine with changing to whatever is appropriate.

**Comment by nturaga** [comment]
Yes, that still isn't introducing a bug in debian stretch (RELEASE_3_10). I'm testing `libmariadb-dev` on buster to see if it fits our needs. It currently doesn't introduce the bug for Rstudio, but I need to check if Bioconductor packages which depend on it install successfully.

**Comment by nturaga** [comment]
This is now resolved. The latest release_base2 and devel_base2 images work as expected.

**Comment by drisso** [comment]
Not sure if this is the right place to put this, but I've encountered the same error running:

```
docker run -e PASSWORD=bioc -p 8787:8787 bioconductor/devel_core2
```

so perhaps the same fix should be applied to *_core2 images?

**Comment by lshep** [comment]
I've just kicked off the rebuild of devel_core it should be available shortly.

**Comment by nturaga** [comment]
The core images have to be rebuilt off the base images.
