### ISSUE TITLE
inconsistent tag names

### ISSUE THREAD

**Issue by nsheff** [Bioconductor/bioc_docker#97]
See, for example: 

"bioconductor/release_base2:R3.6.2_Bioc3.10"

https://hub.docker.com/layers/bioconductor/release_base2/R3.6.2_Bioc3.10/images/sha256-332dd25610d65354ab8aa60d0d1ab8ca0101639c8e1fe10dccee1b563d0187f9

vs "bioconductor/release_base2:R.3.6.1_Bioc3.10"

https://hub.docker.com/layers/bioconductor/release_base2/R.3.6.1_Bioc3.10/images/sha256-b2a590e545bc2ed8f701711088fdd6efc845691378320c682ecda404e48fd5e0

I think there's just an extra period in the 3.6.1 tag, since all the other tags lack that period.

**Comment by lshep** [comment]
Thanks for the heads up.  I think the format of the R3.6.2  is most desirable so we will not make any updates at this time.  
As a heads up:  We will be deprecating these docker containers in up coming weeks (2-3)  in favor of bioconductor_docker:devel  and bioconductor_docker:RELEASE_3_10
